# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BrainTeaser' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BrainTeaser
pod 'pop', '~> 1.0'

  target 'BrainTeaserTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
